spring.main.web-environment: false

logging.level:
  # Enable logging of access token request
  org.springframework.web.client: DEBUG

hello.service:
  url: http://localhost:8081

twitter.service:
  url: https://api.twitter.com/1.1

feign.hystrix.enabled: false

security:
  oauth2:
    hello:
      access-token-uri: http://localhost:8081/oauth/token
      client-id: theId
      client-secret: theSecret
      scope: theScope
    twitter:
      access-token-uri: https://api.twitter.com/oauth2/token
      # Credentials goes to /src/main/resources/config/application.yml
      #client-id:
      #client-secret:
